"use strict";
const userName = "John";
let age = 25;
const email = "john@example.com";
const isSubscribed = true;
let city = "Bangalore";
let loginCount = 5;
let userProfileMessage = `Hello ${userName}, you are ${age} years old and your email is ${email}.`;
console.log("User Profile Message:");
console.log(userProfileMessage);
age = age + 1;
let isEligibleForPremium = age > 18 && isSubscribed;
let isAdult = age >= 18;
console.log("\nUpdated Details:");
console.log(`Updated Age: ${age}`);
console.log(`City (Inferred): ${city}`);
console.log(`Login Count (Inferred): ${loginCount}`);
console.log(`Is Adult: ${isAdult}`);
console.log(`Is Subscribed: ${isSubscribed}`);
console.log(`Eligible for Premium Plan: ${isEligibleForPremium}`);
